#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# BEChessWeb — one-shot setup script for Debian 13 (trixie)
#
# Cài Docker Engine + compose plugin, clone repo, config .env, bật stack
# (nginx + client + server + mongo) qua docker compose, xin cert HTTPS qua
# certbot cho domain công khai.
#
# CÁCH DÙNG:
#   sudo DOMAIN=chess-v2.ttlab.manhthao.uk \
#        EMAIL=longle12042006a@gmail.com \
#        MONGO_URI='mongodb+srv://...' \
#        bash setup-debian13.sh
#
# Biến tuỳ chọn:
#   REPO_URL    (mặc định: https://github.com/phong571737/BEChessWeb.git)
#   REPO_DIR    (mặc định: /opt/BEChessWeb)
#   BRANCH      (mặc định: dev/esp-fen)
#   APP_PORT    (mặc định: 80   — port nginx listen trên host, http→https redirect)
#   SKIP_TLS    (set =1 để bỏ qua certbot, chỉ chạy HTTP — dùng cho LAN/demo)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
DOMAIN="${DOMAIN:?Phải set DOMAIN, vd: DOMAIN=chess-v2.ttlab.manhthao.uk}"
EMAIL="${EMAIL:?Phải set EMAIL cho Let's Encrypt}"
MONGO_URI="${MONGO_URI:?Phải set MONGO_URI (Atlas hoặc mongodb://...)}"
REPO_URL="${REPO_URL:-https://github.com/phong571737/BEChessWeb.git}"
REPO_DIR="${REPO_DIR:-/opt/BEChessWeb}"
BRANCH="${BRANCH:-dev/esp-fen}"
APP_PORT="${APP_PORT:-80}"
SKIP_TLS="${SKIP_TLS:-0}"

log() { printf '\033[1;36m[setup]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Chạy bằng sudo / root"

# ── 1. Cập nhật hệ thống + tool cơ bản ──────────────────────────────────────
log "Cập nhật apt và cài tool cơ bản"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg git ufw openssl python3 cron

# ── 2. Cài Docker Engine + compose plugin (repo official cho Debian trixie) ─
if ! command -v docker >/dev/null 2>&1; then
    log "Cài Docker Engine"
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        > /etc/apt/sources.list.d/docker.list
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
else
    log "Docker đã có, bỏ qua bước cài"
fi

# ── 3. Mở firewall (ufw) ────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1; then
    log "Mở port 22/80/443 trên ufw"
    ufw allow OpenSSH || true
    ufw allow 80/tcp  || true
    ufw allow 443/tcp || true
    yes | ufw enable  || true
fi

# ── 4. Clone / pull repo ────────────────────────────────────────────────────
if [[ -d "$REPO_DIR/.git" ]]; then
    log "Repo đã tồn tại, pull bản mới ($BRANCH)"
    git -C "$REPO_DIR" fetch --all --prune
    git -C "$REPO_DIR" checkout "$BRANCH"
    git -C "$REPO_DIR" pull --ff-only
else
    log "Clone $REPO_URL → $REPO_DIR"
    git clone --branch "$BRANCH" "$REPO_URL" "$REPO_DIR"
fi
cd "$REPO_DIR"

# ── 5. Sinh .env ở root ─────────────────────────────────────────────────────
log "Ghi .env"
ORIGIN_SCHEME="https"
[[ "$SKIP_TLS" == "1" ]] && ORIGIN_SCHEME="http"

cat > .env <<EOF
# auto-generated by setup-debian13.sh on $(date -Iseconds)
MONGO_URI=$MONGO_URI
APP_PORT=$APP_PORT
ALLOWED_ORIGINS=${ORIGIN_SCHEME}://${DOMAIN}
EOF
chmod 600 .env

# ── 6. Cấu hình nginx cho HTTPS ─────────────────────────────────────────────
# Nếu bật TLS: viết lại nginx/default.conf để listen 443 + redirect 80→443.
# Cert sẽ được mount từ /etc/letsencrypt vào container.
if [[ "$SKIP_TLS" != "1" ]]; then
    log "Cài certbot và xin cert cho $DOMAIN"
    apt-get install -y --no-install-recommends certbot

    # Tạo thư mục webroot trước khi mount vào nginx container
    mkdir -p /var/www/certbot

    # Tạm dừng riêng nginx container (nếu đang chạy) để giải phóng port 80.
    # Dùng `stop` thay vì `down` để khỏi gỡ luôn server/client/mongo.
    docker compose stop nginx 2>/dev/null || true

    # Standalone mode (cần port 80 trống)
    certbot certonly --standalone --non-interactive --agree-tos \
        --email "$EMAIL" -d "$DOMAIN" --keep-until-expiring

    log "Viết lại nginx/default.conf cho HTTPS"
    cat > nginx/default.conf <<'NGINX'
upstream chess_server { server server:8080; }
upstream chess_client { server client:3000; }

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name _;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    http2  on;
    server_name __DOMAIN__;

    ssl_certificate     /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # Socket.IO — WebSocket upgrade
    location /socket.io/ {
        proxy_pass         http://chess_server;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 3600s;
    }

    # REST API → Express
    location ~ ^/(games|moves|boards|eval) {
        proxy_pass       http://chess_server;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Everything else → Next.js
    location / {
        proxy_pass         http://chess_client;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
NGINX
    sed -i "s|__DOMAIN__|$DOMAIN|g" nginx/default.conf

    # Patch docker-compose: cho nginx mount cert + mở port 443
    if ! grep -q 'letsencrypt' docker-compose.yml; then
        log "Patch docker-compose.yml để mount cert và mở 443"
        # Thay block ports/volumes của nginx
        python3 - <<'PY'
import re, pathlib
p = pathlib.Path("docker-compose.yml")
s = p.read_text()
new_block = """  nginx:
    image: nginx:alpine
    container_name: chess-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - server
      - client
    networks:
      - chess-net"""
s = re.sub(r"  nginx:\n(?:    .*\n)+?(?=\n[a-z]|\Z)", new_block + "\n", s, count=1)
p.write_text(s)
PY
    fi

    # ── 7. Cron auto-renew cert ────────────────────────────────────────────
    log "Cài cron renew cert"
    cat > /etc/cron.d/bechess-certbot <<EOF
0 3 * * * root certbot renew --quiet --deploy-hook "docker compose -f $REPO_DIR/docker-compose.yml exec -T nginx nginx -s reload"
EOF
fi

# ── 8. Build & up cả 4 service (mongo + server + client + nginx) ────────────
log "docker compose build + up"
docker compose pull mongo nginx || true
docker compose build           # build cả server (Express) và client (Next.js)
docker compose up -d           # start mongo, server, client, nginx

# ── 9. Sanity check — chờ container lên và verify health ────────────────────
log "Đợi container khởi động (15s)..."
sleep 15

log "Trạng thái stack:"
docker compose ps

# Kiểm tra từng service riêng
EXPECTED=(chess-mongo chess-server chess-client chess-nginx)
ALL_OK=1
for name in "${EXPECTED[@]}"; do
    if docker ps --filter "name=^/${name}$" --filter "status=running" --format '{{.Names}}' | grep -q "$name"; then
        log "  ✓ $name running"
    else
        log "  ✗ $name KHÔNG running — chạy 'docker compose logs $name' để xem lỗi"
        ALL_OK=0
    fi
done

# Smoke test backend + frontend
log "Smoke test:"
if curl -fsS -o /dev/null http://localhost:8080/games 2>/dev/null \
   || curl -fsS -o /dev/null -w '%{http_code}' http://127.0.0.1 2>/dev/null | grep -qE '^(200|301|302|404)$'; then
    log "  ✓ Backend (server:8080) phản hồi"
else
    log "  ⚠ Backend chưa phản hồi — có thể đang khởi động, đợi thêm rồi check"
fi

if curl -fsS -o /dev/null -w '%{http_code}' http://127.0.0.1 2>/dev/null | grep -qE '^(200|301|302)$'; then
    log "  ✓ Frontend (client:3000 qua nginx:80) phản hồi"
else
    log "  ⚠ Frontend chưa phản hồi"
fi

log ""
if [[ $ALL_OK -eq 1 ]]; then
    log "═════════════════════════════════════════════════"
    log " ✅ XONG — cả frontend + backend đã chạy"
    log "═════════════════════════════════════════════════"
else
    log "═════════════════════════════════════════════════"
    log " ⚠ Có service chưa lên — xem log để debug"
    log "═════════════════════════════════════════════════"
fi
log ""
log "  Web (frontend)                : ${ORIGIN_SCHEME}://${DOMAIN}"
log "  API (backend, qua nginx)      : ${ORIGIN_SCHEME}://${DOMAIN}/games, /moves, /boards, /eval"
log "  Socket.IO (qua nginx)         : ${ORIGIN_SCHEME}://${DOMAIN}/socket.io/"
log "  ESP32 Server URL (BLE form)   : ${ORIGIN_SCHEME}://${DOMAIN}"
log ""
log "Lệnh hữu ích (chạy trong $REPO_DIR):"
log "  docker compose logs -f                    # tail log tất cả"
log "  docker compose logs -f server             # chỉ backend"
log "  docker compose logs -f client             # chỉ frontend"
log "  docker compose ps                         # trạng thái container"
log "  docker compose restart server             # restart backend"
log "  docker compose restart client             # restart frontend"
log "  docker compose down && docker compose up -d --build   # rebuild toàn bộ"
log "  git pull && docker compose up -d --build  # cập nhật code + redeploy"
